// packages/svelte/src/ChatIva.svelte
<!--
  @component
  Svelte wrapper for `<chat-iva>` — the main Chativa chat panel. Renders
  nothing on the server and until `@chativa/ui` has loaded on the client, so
  it is safe to use in SvelteKit SSR/prerendered routes.

  ```svelte
  <ChatIva connector={dummy} onmessage={(m) => console.log(m)} />
  ```
-->
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import {
    chatStore,
    EventBus,
    type ConnectorStatus,
    type EventBusEventName,
    type EventBusPayloadMap,
    type IncomingMessage,
    type OutgoingMessage,
    type SurveyPayload,
  } from "@chativa/core";
  import { loadChativaUi } from "./internal/loadChativaUi.js";
  import { connectorNameOf, resolveConnectorName } from "./internal/resolveConnector.js";
  import type { ChatIvaProps } from "./types.js";

  type Props = ChatIvaProps;

  let {
    connector,
    fullscreenOnly = false,
    class: className,
    style,
    children,
    element = $bindable(null),
    onmessage,
    onmessagesent,
    onconnect,
    ondisconnect,
    onsurveysubmit,
    onwidgetopen,
    onwidgetclose,
  }: Props = $props();

  let loaded = $state(false);

  // Legacy `on:event` compatibility for Svelte 5 apps that still use the
  // Svelte 4 event syntax (`<ChatIva on:message={(e) => e.detail} />`).
  // Callback props are the primary API; this only reaches listeners that a
  // legacy-mode parent attached, and costs nothing otherwise.
  const dispatch = createEventDispatcher<{
    message: IncomingMessage;
    messagesent: OutgoingMessage;
    connect: undefined;
    disconnect: { status: ConnectorStatus };
    surveysubmit: SurveyPayload;
    widgetopen: undefined;
    widgetclose: undefined;
  }>();

  // `$effect.pre` runs on the client only, before the DOM is updated — so
  // this completes before `<chat-iva>` is created below. `ChatWidget`'s
  // connectedCallback prefers `chatStore.activeConnector` (whenever it isn't
  // the default "dummy") over its own `connector` property, and decides its
  // window mode while connecting, so the shared store is the one channel
  // that is guaranteed to be read in time. `fullscreenOnly={false}` is
  // deliberately not the inverse: it means "no opinion", so it never
  // re-enables a fullscreen toggle the theme turned off.
  $effect.pre(() => {
    const name = resolveConnectorName(connector);
    if (name !== undefined && chatStore.getState().activeConnector !== name) {
      chatStore.getState().setConnector(name);
    }
    if (fullscreenOnly) {
      const theme = chatStore.getState();
      if (!theme.isFullscreen) theme.setFullscreen(true);
      if (theme.allowFullscreen) theme.setAllowFullscreen(false);
    }
  });

  // Callback props are read when an event fires (not when subscribing), so
  // the latest handler is always the one invoked and swapping a handler
  // never re-subscribes.
  $effect(() => {
    const offs: Array<() => void> = [];
    const on = <K extends EventBusEventName>(
      event: K,
      handler: (payload: EventBusPayloadMap[K]) => void,
    ) => {
      EventBus.on(event, handler);
      offs.push(() => EventBus.off(event, handler));
    };
    on("message_received", (message) => {
      onmessage?.(message);
      dispatch("message", message);
    });
    on("message_sent", (message) => {
      onmessagesent?.(message);
      dispatch("messagesent", message);
    });
    on("survey_submitted", (payload) => {
      onsurveysubmit?.(payload);
      dispatch("surveysubmit", payload);
    });
    on("widget_opened", () => {
      onwidgetopen?.();
      dispatch("widgetopen");
    });
    on("widget_closed", () => {
      onwidgetclose?.();
      dispatch("widgetclose");
    });
    on("connector_status_changed", (payload) => {
      if (payload.status === "connected") {
        onconnect?.();
        dispatch("connect");
      } else if (payload.status === "disconnected" || payload.status === "error") {
        ondisconnect?.(payload);
        dispatch("disconnect", payload);
      }
    });
    return () => offs.forEach((off) => off());
  });

  onMount(() => {
    let cancelled = false;
    void loadChativaUi().then(() => {
      if (!cancelled) loaded = true;
    });
    return () => {
      cancelled = true;
    };
  });

  const elementProps = $derived.by(() => {
    const props: Record<string, string> = {};
    const name = connectorNameOf(connector);
    if (name !== undefined) props.connector = name;
    if (className !== undefined) props.class = className;
    if (style !== undefined) props.style = style;
    return props;
  });
</script>

{#if loaded}
  <chat-iva bind:this={element} {...elementProps}>
    {@render children?.()}
  </chat-iva>
{/if}

// packages/react/src/ChatIva.tsx
"use client";

import * as React from "react";
import { chatStore } from "@chativa/core";
import type {
  IConnector,
  IncomingMessage,
  OutgoingMessage,
  SurveyPayload,
  ConnectorStatus,
} from "@chativa/core";
import { loadChativaUi } from "./internal/loadChativaUi";
import { createLazyElementComponent } from "./internal/createLazyElementComponent";
import { resolveConnectorName } from "./internal/resolveConnector";
import { useChativaEvent } from "./hooks/useChativaEvent";

export interface ChatIvaProps {
  /** Connector name (already registered elsewhere) or an `IConnector` instance to auto-register and use. Defaults to whatever `<ChativaProvider>` (or `window.chativaSettings`) has activated. */
  connector?: string | IConnector;
  /**
   * Start in fullscreen and hide the fullscreen toggle. Equivalent to the
   * `fullscreen-only` HTML attribute on `<chat-iva>`.
   */
  fullscreenOnly?: boolean;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
  /** A bot/connector message was delivered. */
  onMessage?: (message: IncomingMessage) => void;
  /** The user sent a message. */
  onMessageSent?: (message: OutgoingMessage) => void;
  /** The connector transitioned to `"connected"`. */
  onConnect?: () => void;
  /** The connector transitioned to `"disconnected"` or `"error"`. */
  onDisconnect?: (payload: { status: ConnectorStatus }) => void;
  /** The end-of-conversation survey was submitted. */
  onSurveySubmit?: (payload: SurveyPayload) => void;
  /** The chat panel opened. */
  onWidgetOpen?: () => void;
  /** The chat panel closed. */
  onWidgetClose?: () => void;
}

interface ChatIvaElementProps {
  connector?: string;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}

let cachedChatIva: React.ComponentType<
  ChatIvaElementProps & React.RefAttributes<HTMLElement>
> | null = null;

async function loadChatIvaElement() {
  if (cachedChatIva) return cachedChatIva;
  const [{ createComponent }, { ChatWidget }] = await Promise.all([
    import("@lit/react"),
    loadChativaUi(),
  ]);
  cachedChatIva = createComponent({
    react: React,
    tagName: "chat-iva",
    elementClass: ChatWidget,
  }) as unknown as React.ComponentType<ChatIvaElementProps & React.RefAttributes<HTMLElement>>;
  return cachedChatIva;
}

const LazyChatIva = createLazyElementComponent<ChatIvaElementProps, HTMLElement>(
  loadChatIvaElement,
  "LazyChatIva",
);

/**
 * React wrapper for `<chat-iva>` — the main Chativa chat widget (launcher +
 * panel). Renders nothing until the underlying `@chativa/ui` module has
 * loaded on the client, so it's safe to render from a Server Component tree.
 *
 * @example
 * ```tsx
 * import { ChatIva } from "@chativa/react";
 * import { DummyConnector } from "@chativa/connector-dummy";
 *
 * const dummy = new DummyConnector();
 *
 * <ChatIva connector={dummy} onMessage={(m) => console.log(m)} />
 * ```
 */
export const ChatIva = React.forwardRef<HTMLElement, ChatIvaProps>(function ChatIva(
  {
    connector,
    fullscreenOnly,
    onMessage,
    onMessageSent,
    onConnect,
    onDisconnect,
    onSurveySubmit,
    onWidgetOpen,
    onWidgetClose,
    ...rest
  },
  ref,
) {
  // Idempotent registry write — safe during render (mirrors how
  // ChatWidget.connectedCallback itself resolves the active connector), and
  // must complete before the underlying element connects.
  const connectorName = resolveConnectorName(connector);

  // `@lit/react` sets element properties via a ref, which React only runs
  // *after* the DOM node is inserted — but `ChatWidget.connectedCallback`
  // reads `this.connector` synchronously at connect time, before that ref
  // fires. Pushing the resolved name into the shared `chatStore` instead
  // works: `ChatWidget` prefers `themeState.activeConnector` over its own
  // `connector` property whenever the former isn't the default "dummy".
  if (connectorName !== undefined && chatStore.getState().activeConnector !== connectorName) {
    chatStore.getState().setConnector(connectorName);
  }

  // Same reasoning as the connector above, and the same reason it is applied
  // here rather than handed to the element as a `fullscreenOnly` property:
  // `<chat-iva>` decides its window mode while connecting, and `@lit/react`
  // only assigns element properties afterwards — late enough to render one
  // non-fullscreen frame first, and not at all in its `node` build. Writing to
  // the shared store is the one path that works before the element connects.
  // `false` is deliberately not the inverse: it means "no opinion", so it never
  // re-enables a fullscreen toggle the theme turned off.
  if (fullscreenOnly) {
    const theme = chatStore.getState();
    if (!theme.isFullscreen) theme.setFullscreen(true);
    if (theme.allowFullscreen) theme.setAllowFullscreen(false);
  }

  useChativaEvent("message_received", onMessage);
  useChativaEvent("message_sent", onMessageSent);
  useChativaEvent("survey_submitted", onSurveySubmit);
  useChativaEvent("widget_opened", onWidgetOpen);
  useChativaEvent("widget_closed", onWidgetClose);
  useChativaEvent("connector_status_changed", (payload) => {
    if (payload.status === "connected") onConnect?.();
    else if (payload.status === "disconnected" || payload.status === "error") onDisconnect?.(payload);
  });

  const elementProps: ChatIvaElementProps = { ...rest };
  if (connectorName !== undefined) elementProps.connector = connectorName;

  return <LazyChatIva ref={ref} {...elementProps} />;
});
